//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFine.MySQLModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bas_warehouse
    {
        public string F_Id { get; set; }
        public string F_CorpID { get; set; }
        public string F_Code { get; set; }
        public string F_Name { get; set; }
        public string F_Address { get; set; }
        public string F_Contact { get; set; }
        public string F_Tel { get; set; }
        public string F_MobilePhone { get; set; }
        public Nullable<bool> F_IsBin { get; set; }
        public Nullable<bool> F_IsRequireReceive { get; set; }
        public Nullable<bool> F_IsRequireShipment { get; set; }
        public Nullable<bool> F_DeleteMark { get; set; }
        public Nullable<bool> F_EnabledMark { get; set; }
        public string F_Description { get; set; }
        public System.DateTime F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
        public System.DateTime F_LastModifyTime { get; set; }
        public string F_LastModifyUserId { get; set; }
        public System.DateTime F_DeleteTime { get; set; }
        public string F_DeleteUserId { get; set; }
    }
}
